### ISSUE TITLE
No sound noVNC

### ISSUE THREAD

**Issue by kmille36** [vexingcodes/dwarf-fortress-docker#2]
I tried, it no sound.

**Comment by legojesus** [comment]
I also had no sound. After connecting to the container and examining the logs, looks like audiostream doesn't have an actual IP address for "localhost". 

I went into the `supervisor.conf` file in this repo and changed all "localhost" references to "127.0.0.1", rebuilt the docker image and things work as expected with sound.

**Comment by legojesus** [comment]
I managed to run Heroes of Might & Magic 3 with sound, check it out: https://github.com/legojesus/dos-games-in-browser-docker/tree/main/HoMM3

There's still a slight delay but it works!
